### ISSUE TITLE
Non Standard Images in News Feed

### ISSUE THREAD

**Issue by SimplyFaisal** [gt-big-data/retina-ui#14]
Some of the images  in the news feed differ in size from the others:
![screenshot from 2014-09-19 02 58 12](https://cloud.githubusercontent.com/assets/4655100/4331787/58a2fd08-3fca-11e4-857b-b8bc32fdb304.png)
It would be nice if we could change the layout of the tiles so that all the images display in a standard manner.

**Comment by nathancheek** [comment]
Given the importance we have been placing on articles having images, what do we do when inevitably we don't have an image? I propose instead of extremely limiting where such an article could be located on the site, we (randomly?) assign such articles a color/texture that could be used instead. So if we have a mural of articles, we can include these articles hopefully without them looking too out of place.

See my (current pull request)[https://github.com/gt-big-data/retina-ui/pull/38] about front page design for example of news article mural:
!(Mural example)[https://cloud.githubusercontent.com/assets/3259614/8893047/9fbd146e-334c-11e5-8501-0e70f45b1f7b.png]
